### ISSUE TITLE
Prompt数据集是否可以开源

### ISSUE THREAD

**Issue by aidejieceng** [cocacola-lab/ChatIE#1]
您好，很棒的一篇工作。
请问会不会将经过Prompt转换后的数据集分享出来 :)

**Comment by threeColorFr** [comment]
你把数据集里的句子填到prompt template中就行了。模板见docs/prompts文件夹

**Comment by suexin27** [comment]
您好，我还想问一下数据集是一句一句测的吗？还是可以整个上传后一起完成抽取呢，谢谢🙏

**Comment by suexin27** [comment]
还有你们的prompt template是人工定义的吧，定义时有没有考虑测试更换不同的template内容呢？

**Comment by suexin27** [comment]
您好，请问处理批量数据（一个数据集文件）做抽取的代码可以发一下吗？谢谢。

**Comment by zhanghaok** [comment]
> 你把数据集里的句子填到prompt template中就行了。模板见docs/prompts文件夹

请问使用prompt后输出了下面干扰的话，你们是如何处理呢
![image](https://github.com/cocacola-lab/ChatIE/assets/39120036/102b44bd-5428-4df7-997e-c8e85aac1472)

**Comment by threeColorFr** [comment]
见tool里脚本，用正则表达式提取。
