### ISSUE TITLE
Incorrect API key

### ISSUE THREAD

**Issue by kbwzy** [cocacola-lab/ChatIE#11]
"error-stage1:Incorrect API key provided: sk-5ZHQn*****************************************************************************************pYxy. You can find your API key at https://platform.openai.com/account/api-keys."

![image](https://user-images.githubusercontent.com/12123683/232979695-02b10c98-9604-42e8-88b1-b3bf51a13072.png)
请问下API key测试可用，为啥代码里面报错incorrect api key

**Comment by threeColorFr** [comment]
这个api key应该已经过期了
