### ISSUE TITLE
event detection performance on the ACE2005 dataset

### ISSUE THREAD

**Issue by yzqtdu** [cocacola-lab/ChatIE#15]
hello,  did you  test the event detection performance (trigger identification and trigger classification) on the ACE2005 dataset ? According to the paper, only contain arguments classification are considered.  Did I miss anything?

**Comment by threeColorFr** [comment]
You are right, only event type and arguments extraction are considered. But we have added trigger recognition and classification experiments, which will be added to the new version of the paper.

**Comment by yzqtdu** [comment]
ok, hope to see it soon
