### ISSUE TITLE
关于Vanilla Prompt

### ISSUE THREAD

**Issue by suexin27** [cocacola-lab/ChatIE#3]
你好，
  我看论文中的你们对“Vanilla Prompt vs. Our Chat-based Prompt”做了对比，这里的Vanilla Prompt具体有文章吗？是哪篇文章做的提示学习吗？想了解下，方便解释一下吗，谢谢。

**Comment by threeColorFr** [comment]
Vanilla means the single-turn prompt and you can refer to the docs/prompts folder; the evaluation method is written in the paper, and you can refer to the specific link.

**Comment by suexin27** [comment]
thank you~
