### ISSUE TITLE
access token问题

### ISSUE THREAD

**Issue by Yichuilan** [cocacola-lab/ChatIE#8]
{"detail":{"message":"Your authentication token has expired. Please try signing in again.","type":"invalid_request_error","param":null,"code":"token_expired"}} OpenAI: {"detail":{"message":"Your authentication token has expired. Please try signing in again.","type":"invalid_request_error","param":null,"code":"token_expired"}} (code: 401)
以上是错误信息
应该是指access token过期了。
不太懂access token这个是什么意思，和openai的key有关吗？如何修复？

**Comment by threeColorFr** [comment]
这个是账号过期了，你或许可以自己注册一个账号把自己的openaikey换上

**Comment by Yichuilan** [comment]
我使用的是自己的key，问题好像出在access token过期了，access token应该是用来连接反向代理服务器的，一直用的代码中给的access token ，如下
df_access = [
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJkYWVydWdvc2h1bW96aGFlMUBob3RtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJnZW9pcF9jb3VudHJ5IjoiVVMifSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLVZtMUZOaXRTVmhqQ2pBQ0NJTXhXZjRWSCJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiYXV0aDB8NjM0ZmM0YjQzMjdhMTE0ZDQ0MmI2NmViIiwiYXVkIjpbImh0dHBzOi8vYXBpLm9wZW5haS5jb20vdjEiLCJodHRwczovL29wZW5haS5vcGVuYWkuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY3NzU3NDE4MCwiZXhwIjoxNjc4NzgzNzgwLCJhenAiOiJUZEpJY2JlMTZXb1RIdE45NW55eXdoNUU0eU9vNkl0RyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9mZmxpbmVfYWNjZXNzIn0.EqqwkD-30BIgbRzRemn8sh0flzskBgf50t44Nf7gU-pqqBSBlHgWPChSMefuKzlbdM-WCOJ-bjv5VaitaNUH4_9dtyajqdx93wjBo0MouSBk2LAz13I-JbsVFti0QqaEYGpxc0t7IjY-Y7FLfWwLtCGQe-7miYKjLTF29ME1N0_zb4pK7vrtmNGlEZfchWEy-Qb6cIqR3uOMNLYs6EAAiCWZMGe4T3xmE5PtQaafpg6FSAmE6Bhxz2hN29H5fxs446L__VeyPxUcrwGy48X0g0H9RaZm-YMrB5nuRi8ehxyuScqP8JHTPYYnsEjlwtS_cuW8qDZ4g5vUrnLkUf8LNg',
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJuYWV2eWxlbGViZXNoZUBob3RtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJnZW9pcF9jb3VudHJ5IjoiVVMifSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLVQ5ZG5vVmYwVmJMQ09LRjF1N0xuVVpmSiJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiYXV0aDB8NjM0ZmM0MTgwZmE4NjlkYTZiZmM5ZTM2IiwiYXVkIjpbImh0dHBzOi8vYXBpLm9wZW5haS5jb20vdjEiLCJodHRwczovL29wZW5haS5vcGVuYWkuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY3NzU3NDQ5NSwiZXhwIjoxNjc4Nzg0MDk1LCJhenAiOiJUZEpJY2JlMTZXb1RIdE45NW55eXdoNUU0eU9vNkl0RyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9mZmxpbmVfYWNjZXNzIn0.2QXw7g8kIn1jsX2T-owUfNwPikFKX_SmoX7G3kRg7ytA5GcxJsqxVqydS8k4o2kCAJdHyR8MHe2Lef_ZVtlGEb8_u1DaJyCjZdki7gqjdPIx5X0FwnHKquwN_pQPs90Bkwi6N5iEq5HczwUFpALMxryrVSG2Q0UiuabUa2GwtmPu6OVAQD1NIh_sN1479kbEZ0TWYm49ZWP-4uJkxny_fqPMcEn-YWJou-P0pEjPS-hWusLzUbkE5zSXLu4oqGaAtFjutYwKd-WGrGLexHG-eQGtABfX-l2bNG8_f9qdtKLpk7uY66mXcmFLBFKEfNVP3KWe7Pipdxwt4blDQMhmPg',
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ0YWZvb3Nocm9oQGhvdG1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImdlb2lwX2NvdW50cnkiOiJVUyJ9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsidXNlcl9pZCI6InVzZXItd1RFalpva1ZSdU1sSGVPckJvd2dFTURVIn0sImlzcyI6Imh0dHBzOi8vYXV0aDAub3BlbmFpLmNvbS8iLCJzdWIiOiJhdXRoMHw2MzZkYjYzMmM0ZDM3MzNhYTJjNTA1NWQiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjc3NTc0ODAxLCJleHAiOjE2Nzg3ODQ0MDEsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb2ZmbGluZV9hY2Nlc3MifQ.pBk5GSZrtQZNiJTmodXJqkyeYw1Z-fACSzbgP4yzgH6T40VZDZHUGXn3_z4uDOUr8_pezCCtehtrIGKmGFSFojaOjijUsGeEzcDQttSZe54JPRkuKLDlr7971CeNhPduUuqMdd49IqpdBC9Xr77oZjXOvyyca3ohpShSznK4D0JJ7AWiTMdbeeA5uUP0l0_y425W804dm99XL6kE19RdZSe3KKeDJ8jsvJc3tfez3tfS9xpRk4V8kar9w4rhchTd02MXToDwSGPKTC9M0MDUtb3lrgviWjfbZx7Yfa8GFtkAr3rWWtNqeXnjboW7__2rkWt-8PMiVSmNAEKEtqvWJw',
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ0ZXNoYXN0am5zZEBob3RtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJnZW9pcF9jb3VudHJ5IjoiVVMifSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLUJ2dzA1WHlybkU0aFNtUmlvakpRcW1DMyJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiYXV0aDB8NjM2ZGI2ZDA2N2Q1ZWRmZjRhYWFlYjc5IiwiYXVkIjpbImh0dHBzOi8vYXBpLm9wZW5haS5jb20vdjEiLCJodHRwczovL29wZW5haS5vcGVuYWkuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY3NzU3NDk4OCwiZXhwIjoxNjc4Nzg0NTg4LCJhenAiOiJUZEpJY2JlMTZXb1RIdE45NW55eXdoNUU0eU9vNkl0RyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9mZmxpbmVfYWNjZXNzIn0.m1DVHRcZCK7zStGuF5vpUo01ZPAodzBXn79XKuOzrNebtdYL3sFax9f-2LKb6wCl8SzGq2QIzjEr3nmyGdtiEYyWN6toOmPXk5P90kZNiOOpCmsLY7NLJsHbqUGJkze0SvWD4lAgAzNhqn5y1Y6iOAxHjr-pAw5aeZYVaWWK7v2xmN6KjP7VmqfbzSCZIWHVq11fckgk5gZdQsZQxCkJbApqex9ARDZe5M08pXvCgjaeTkq8UqSdeCFHDKPL1kBCSQmpHMjj5_zYgdvOlNzHzJEjxQ7FzZpaQ1ZOB3CM07OyyKMb6h9aAnmU8QfC3vA1282ILmdK-yCZsHGZhVU1Tw',
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ2ZWFuZGV3bWNvcW5AaG90bWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZ2VvaXBfY291bnRyeSI6IlVTIn0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJ1c2VyX2lkIjoidXNlci10VU5reG5NNUJ0NWlEck92S0hNcm12RXkifSwiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsInN1YiI6ImF1dGgwfDYzNmRiN2IwYTUxMzZmM2I5ODVhOThhYSIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2Nzc1NzUxNjEsImV4cCI6MTY3ODc4NDc2MSwiYXpwIjoiVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG1vZGVsLnJlYWQgbW9kZWwucmVxdWVzdCBvcmdhbml6YXRpb24ucmVhZCBvZmZsaW5lX2FjY2VzcyJ9.cArZLyqKkMZBud_olNeJsmX4jL5ijKJxVtd8lZTSRXHbNgZOI2vM1800ulLD8J8zuFluqPzSry2ngLZwK4ymRbf_2vCGJSJVzCFWje_ysUKNTVhoBOedudYudqUd2iaxoSuIfX51OYebJ2p9SFijUn8Ljaqx9E6neTm-lkKuPEMQlvzNw6NneOk1o511ECUpfVWO7iTgUqlABePI9P4F-E1QDAf8X0ji4lAl25ttc1IGWvKr1gY71LxW4OgzuY5LLD1ImbF4AZJ2p7_h7zs9p4zG28QttRxBCmM00lTG2oIzsvcpEaTuLTlJaOsXxyJxohDbo-GfRd_OJAWu8byrTw',
]

**Comment by threeColorFr** [comment]
你的access token为什么这么长
